"prefix" = "S"
"members" = ["ysy", "jhr", "ljw", "kcy", "kyy", "ksm", "knk", "gyb", "ked"]
"random" = false
"gravity" = [
    ["8", "aaa", "kre"]
]
"colors" = [
    ["orange", "#ff8000"],
    ["yellow", "#ffff00"],
    ["mint", "#00ff80"],
    ["purple", "#8000ff"],
    ["pink", "#ff0088"]
]
