#"prefix" = "S"
#"members" = ["ysy", "jhr", "ljw", "kcy", "kyy", "ksm", "knk", "gyb", "ked"]
"prefix" = "L"
"members" = ["heejin", "hyunjin", "haseul", "yeojin", "vivi", "kimlip", "jinsoul", "choerry", "yves", "chuu", "gowon", "hyejoo"]
"random" = false
"gravity" = [
    ["8", "aaa", "kre"],
    ["12", "1/3", "oec", "yyxy"]
]
